// GENERATED BY SIDDHARTH R BHARDWAJ, 22112028
var numberofdrums = document.querySelectorAll(".drum").length;

for (i = 0; i < numberofdrums; i++) {
  document.querySelectorAll(".drum")[i].addEventListener("click", function () {
      makeSound(this.innerHTML);
  });}
   document.addEventListener("keypress",function(event){
       makeSound(event.key);
   });

   function makeSound(event){
    switch (event) {
      case "w":
        var audio = new Audio("audios/crash.mp3");
        audio.play();
        break;
      case "z":
        var audio = new Audio("audios/crash.mp3");
        audio.play();
        break;
      case "f":
        var audio = new Audio("audios/crash.mp3");
        audio.play();
        break;
      case "t":
        var audio = new Audio("audios/crash.mp3");
        audio.play();
        break;
      // case "a":
      //   var audio = new Audio("audios/tom-2.mp3");
      //   audio.play();
      //   break;
      case "s":
        var audio = new Audio("audios/tom-3.mp3");
        audio.play();
        break;
      case "d":
        var audio = new Audio("audios/tom-4.mp3");
        audio.play();
        break;
      case "j":
        var audio = new Audio("audios/kick-bass.mp3");
        audio.play();
        break;
      case "k":
        var audio = new Audio("audios/snare.mp3");
        audio.play();
        break;
      case "l":
        var audio = new Audio("audios/tom-1.mp3");
        audio.play();
        break;

      default:
          alert("wrongkey")
        break;
      
    }
  };


